spring.application.name=cattlemanager
spring.datasource.url=jdbc:postgresql://localhost:5432/cattlemanager
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8085

# Clave secreta para firmar JWT (cambiar por una aleatoria segura en producción)
app.jwt.secret=Y2F0dGxlbWFuYWdlcnNlY3JldGtleTEyMzQ1Njc4OTAxMjM0NQ==
# Expiración del token: 24 horas en milisegundos
app.jwt.expiration=86400000
